[package]
name = "lang"
version = "0.1.0"
authors = ["Mario Montoya <mamcx@elmalabarista.com>"]
build = "build.rs"

[dependencies]
time = "0.1.0"
rand = "0.5"
num = "*"
bytes = "0.4"
# For parsing -- use master until 0.16 is released
# This is due to some bullshit with the lalrpop_mod macro
lalrpop-util = { git = "https://github.com/lalrpop/lalrpop.git" }
regex = "0.2"

[build-dependencies]
# For parsing
lalrpop = "0.15"
